const options = [
   {
      id: '0',
      model: 'BMW M4 Series',
      image: require('../assets/bmw-m4-white.png'),
      rating: '4.5',
      type: 'New',
      price: '300.000',
      brand: 'bmw',
   },
   {
      id: '1',
      model: 'Chevrolet Camaro',
      image: require('../assets/chevrolet-camaro.png'),
      rating: '4.6',
      type: 'Used',
      price: '188.000',
      brand: 'chevrolet',
   },
   {
      id: '2',
      model: 'BMW M4 Series',
      image: require('../assets/bmw-m4-blue.png'),
      rating: '4.8',
      type: 'New',
      price: '200.000',
      brand: 'bmw',
   },
   {
      id: '3',
      model: 'Suzuki Swift',
      image: require('../assets/suzuki-swift.png'),
      rating: '4.1',
      type: 'New',
      price: '220.000',
      brand: 'suzuki',
   },
   {
      id: '4',
      model: 'Mercedes S-Class',
      image: require('../assets/mercedes-white.png'),
      rating: '4.5',
      type: 'New',
      price: '220.000',
      brand: 'mercedes',
   },
   {
      id: '5',
      model: 'BMW Series 3',
      image: require('../assets/bmw-series-3.png'),
      rating: '4.8',
      type: 'Used',
      price: '120.000',
      brand: 'bmw',
   },
   {
      id: '6',
      model: 'Tesla Model S',
      image: require('../assets/tesla-model-s.png'),
      rating: '5.0',
      type: 'New',
      price: '280.000',
      brand: 'tesla',
   },
   {
      id: '7',
      model: 'Toyota RAV4',
      image: require('../assets/toyota-rav-4.png'),
      rating: '4.3',
      type: 'New',
      price: '280.000',
      brand: 'toyota',
   },
   {
      id: '8',
      model: 'Hyundai Creta',
      image: require('../assets/hyundai-creta.png'),
      rating: '3.5',
      type: 'New',
      price: '200.000',
      brand: 'hyundai',
   },
   {
      id: '9',
      model: 'Volkswagen T Prime',
      image: require('../assets/volkswagen-t-prime.png'),
      rating: '4.5',
      type: 'New',
      price: '150.000',
      brand: 'volkswagen',
   },
];

export default options;
